version: "3.8"

services:
  student-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-server
    ports:
      - "9090:8080"
    networks:
      - student-network
    env_file: 
      - .env  # Load environment variables from .env
    depends_on:
      - student-db

  student-db:
    image: postgres:latest
    container_name: student-db
    env_file: 
      - .env  # Load environment variables from .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - student-network
    volumes:
      - student-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  student-network:
    driver: bridge

volumes:
  student-db-data:
    driver: local
